repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "3.1.2"
    hooks:
      - id: editorconfig-checker
        alias: ec

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
